<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Drivers Licence</name>
   <tag></tag>
   <elementGuidId>0b0d3f62-1327-4ffc-a0d2-4413ab8c9a5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form_licence__main_chosen']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.chosen-single.chosen-default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d8e7b61d-6720-4a0a-844a-904c1ed50de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chosen-single chosen-default</value>
      <webElementGuid>5f078390-bdec-4896-b197-2cd7bc2662dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drivers Licence</value>
      <webElementGuid>9ae9fbe0-f49b-47be-9794-1b026d43544f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_licence__main_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]</value>
      <webElementGuid>e252d1d6-513d-4f37-91a2-5c9752c31ad0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_licence__main_chosen']/a</value>
      <webElementGuid>17332419-13c2-474e-bf2a-e610efa64cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drivers Licence'])[1]/following::a[1]</value>
      <webElementGuid>229c7cd7-46eb-4159-96cc-b91781ad03a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Children'])[1]/following::a[1]</value>
      <webElementGuid>222b7bed-81d0-40f2-9370-fe616aabcac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drivers Licence'])[4]/preceding::a[1]</value>
      <webElementGuid>db548995-19d1-43b0-9a84-a5a57ccbc7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/a</value>
      <webElementGuid>5804aa28-aa6c-4db9-b377-842c8538c2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Drivers Licence' or . = 'Drivers Licence')]</value>
      <webElementGuid>67c07131-4fec-4e0a-982e-44ad8223391f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
