<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Book your Campervan     Pick Up Date 2_553a1d</name>
   <tag></tag>
   <elementGuidId>3ed8c621-ad1f-4ffb-b037-82c2e6730784</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_main']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form_main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>79a826ad-d1f8-4c9a-932e-a47572cde8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>[ bookingComponent ] prepareCountry hasCountry</value>
      <webElementGuid>5ca7b933-3c1f-4585-8b2b-948d47456b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_main</value>
      <webElementGuid>3e39bda7-7a31-41c3-a8c1-b82a9552c8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>75caa3cd-a8f8-48cb-b829-ffd42d9131ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>https://booking.britz.com/search?cc=nz&amp;brand=mby&amp;ac=&amp;sc=rv&amp;vtype=rv&amp;</value>
      <webElementGuid>79a685fa-b22f-429b-b253-f6fc935cabd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Book your Campervan     Pick Up Date 29/04/2022  Pick Up Date is required*     Drop Off Date 21/05/2022  Drop Off Date is required*    PrevNextMay 2022MoTuWeThFrSaSu      12345678910111213141516171819202122232425262728293031        Pick up location Pick Up Location  AucklandChristchurchQueenstown           AucklandAucklandChristchurchQueenstown Pick Up Location is required*Drop Off LocationDrop Off Location  AucklandChristchurchQueenstown     ChristchurchAucklandChristchurchQueenstown Drop Off Location is required*    Passengers Passengers      Adults  1234562123456   Children  0123450012345    Drivers LicenceDrivers Licence AustraliaCanadaChinaDenmarkFranceGermanyNetherlandsNew ZealandSwedenSwitzerlandUnited KingdomUnited States of America--------------------AfghanistanAlbaniaAlgeriaAmerican SamoaAndoraAngolaAnguillaAntarcticaAntigua &amp; BarbadosArgentinaArmeniaArubaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBeninBermudaBoliviaBosnia and HerzegovinaBotswanaBouvet IslandBrazilBritish Indian Ocean TerritoryBruneiBulgariaBurkina FasoBurundiButanCambodiaCameroonCape VerdeCayman IslandsCental African RepublicChadChileChristmas IslandCocos (Keeling) IslandColombiaComorosCongoCook IslandCosta RicaCote D'ivoireCroatiaCubaCyprusCzech RepublicDjiboutiIDominicaDominican RepublicEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEthiopiaFalkland IslandsFaroe IslandsFijiFinlandFranceFrench GuianaFrench PolynesiaFrench Souther TerritoriesGabonGambiaGeorgiaGhanaGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuineaGuinea-BissauGuyanaHaitiHeard and McDonald IslandsHondurasHong KongHungaryIcelandIndiaIndonesiaIranIraqIrelandIsraelItalyJamaicaJapanJordanKazakhstanKenyaKiribatiKuwaitKyrgyzstanLao Peoples Democratic RepublicLatviaLebanonLesothoLiberiaLibyaLiechtensteinLithuaniaLuxembourgMacauMacedoniaMadagascarMalawiMalaysiaMaldivesMaliMaltaMarshall IslandsMartiniqueMauritaniaMauritiusMayotteMexicoMicronesia, Federated States ofMoldovaMonacoMongoliaMontserratMoroccoMozambiqueMyanamarNamibiaNauruNepalNetherlandsNew CaledoniaNicaraguaNigerNigeriaNiueNorfolk IslandNorth KoreaNorthern Mariana IslandsNorwayOmanPakistanPalauPanamaPapua New GuineaParaguayPeruPhilippinesPitcairn IslandsPolandPortugalPuerto RicoQatarReunionRomaniaRussian FederationRwandaSaint HelenaSaint Kitts and NevisSaint LuciaSaint Pierre and MiquelonSaint Vincent and The GrenadinesSamoaSan MarinoSao Tome and PrincipeSaudi ArabiaSenegalSeychellesSingaporeSlovakiaSloveniaSolomon IslandsSomaliaSouth AfricaSouth GeorgiaSouth KoreaSpainSri LankaSudanSurinameSvalbardand Jan Mayen IslandsSyriaTaiwanTajikistanTanzaniaThailandTogoTokelauTongaTrinidad and TobagoTunisiaTurkeyTurkmenistanTurks and Caicos IslandsTuvaluUgandaUkraineUnited Arab EmiratesUruguayUS Minor Outlying IslandsUzbekistanVanuatuVatican CityVenezualaVietnamVirgin Islands (GB)Virgin Islands (US)Wallis and Futuna IslandsWestern SaharaYemenZambiaZimbabweDrivers Licence Drivers Licence is required*  Promo       Search    </value>
      <webElementGuid>1745dedd-580d-4a50-ba2b-61ec864271fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_main&quot;)</value>
      <webElementGuid>21d3f99a-7abc-4b8b-9439-f2a96867b80e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='form_main']</value>
      <webElementGuid>07e8e5fc-9c0e-46e4-bd8e-e9dba3ec9a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Australia'])[2]/following::form[1]</value>
      <webElementGuid>e18040fd-3243-4036-8e7b-b66e40e6e908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Zealand'])[3]/following::form[1]</value>
      <webElementGuid>99d84bc0-4892-4636-b324-7ba799209c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>430b8899-6baa-4c13-b605-abb4c4620f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'form_main' and (text() = concat(&quot;    Book your Campervan     Pick Up Date 29/04/2022  Pick Up Date is required*     Drop Off Date 21/05/2022  Drop Off Date is required*    PrevNextMay 2022MoTuWeThFrSaSu      12345678910111213141516171819202122232425262728293031        Pick up location Pick Up Location  AucklandChristchurchQueenstown           AucklandAucklandChristchurchQueenstown Pick Up Location is required*Drop Off LocationDrop Off Location  AucklandChristchurchQueenstown     ChristchurchAucklandChristchurchQueenstown Drop Off Location is required*    Passengers Passengers      Adults  1234562123456   Children  0123450012345    Drivers LicenceDrivers Licence AustraliaCanadaChinaDenmarkFranceGermanyNetherlandsNew ZealandSwedenSwitzerlandUnited KingdomUnited States of America--------------------AfghanistanAlbaniaAlgeriaAmerican SamoaAndoraAngolaAnguillaAntarcticaAntigua &amp; BarbadosArgentinaArmeniaArubaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBeninBermudaBoliviaBosnia and HerzegovinaBotswanaBouvet IslandBrazilBritish Indian Ocean TerritoryBruneiBulgariaBurkina FasoBurundiButanCambodiaCameroonCape VerdeCayman IslandsCental African RepublicChadChileChristmas IslandCocos (Keeling) IslandColombiaComorosCongoCook IslandCosta RicaCote D&quot; , &quot;'&quot; , &quot;ivoireCroatiaCubaCyprusCzech RepublicDjiboutiIDominicaDominican RepublicEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEthiopiaFalkland IslandsFaroe IslandsFijiFinlandFranceFrench GuianaFrench PolynesiaFrench Souther TerritoriesGabonGambiaGeorgiaGhanaGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuineaGuinea-BissauGuyanaHaitiHeard and McDonald IslandsHondurasHong KongHungaryIcelandIndiaIndonesiaIranIraqIrelandIsraelItalyJamaicaJapanJordanKazakhstanKenyaKiribatiKuwaitKyrgyzstanLao Peoples Democratic RepublicLatviaLebanonLesothoLiberiaLibyaLiechtensteinLithuaniaLuxembourgMacauMacedoniaMadagascarMalawiMalaysiaMaldivesMaliMaltaMarshall IslandsMartiniqueMauritaniaMauritiusMayotteMexicoMicronesia, Federated States ofMoldovaMonacoMongoliaMontserratMoroccoMozambiqueMyanamarNamibiaNauruNepalNetherlandsNew CaledoniaNicaraguaNigerNigeriaNiueNorfolk IslandNorth KoreaNorthern Mariana IslandsNorwayOmanPakistanPalauPanamaPapua New GuineaParaguayPeruPhilippinesPitcairn IslandsPolandPortugalPuerto RicoQatarReunionRomaniaRussian FederationRwandaSaint HelenaSaint Kitts and NevisSaint LuciaSaint Pierre and MiquelonSaint Vincent and The GrenadinesSamoaSan MarinoSao Tome and PrincipeSaudi ArabiaSenegalSeychellesSingaporeSlovakiaSloveniaSolomon IslandsSomaliaSouth AfricaSouth GeorgiaSouth KoreaSpainSri LankaSudanSurinameSvalbardand Jan Mayen IslandsSyriaTaiwanTajikistanTanzaniaThailandTogoTokelauTongaTrinidad and TobagoTunisiaTurkeyTurkmenistanTurks and Caicos IslandsTuvaluUgandaUkraineUnited Arab EmiratesUruguayUS Minor Outlying IslandsUzbekistanVanuatuVatican CityVenezualaVietnamVirgin Islands (GB)Virgin Islands (US)Wallis and Futuna IslandsWestern SaharaYemenZambiaZimbabweDrivers Licence Drivers Licence is required*  Promo       Search    &quot;) or . = concat(&quot;    Book your Campervan     Pick Up Date 29/04/2022  Pick Up Date is required*     Drop Off Date 21/05/2022  Drop Off Date is required*    PrevNextMay 2022MoTuWeThFrSaSu      12345678910111213141516171819202122232425262728293031        Pick up location Pick Up Location  AucklandChristchurchQueenstown           AucklandAucklandChristchurchQueenstown Pick Up Location is required*Drop Off LocationDrop Off Location  AucklandChristchurchQueenstown     ChristchurchAucklandChristchurchQueenstown Drop Off Location is required*    Passengers Passengers      Adults  1234562123456   Children  0123450012345    Drivers LicenceDrivers Licence AustraliaCanadaChinaDenmarkFranceGermanyNetherlandsNew ZealandSwedenSwitzerlandUnited KingdomUnited States of America--------------------AfghanistanAlbaniaAlgeriaAmerican SamoaAndoraAngolaAnguillaAntarcticaAntigua &amp; BarbadosArgentinaArmeniaArubaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBeninBermudaBoliviaBosnia and HerzegovinaBotswanaBouvet IslandBrazilBritish Indian Ocean TerritoryBruneiBulgariaBurkina FasoBurundiButanCambodiaCameroonCape VerdeCayman IslandsCental African RepublicChadChileChristmas IslandCocos (Keeling) IslandColombiaComorosCongoCook IslandCosta RicaCote D&quot; , &quot;'&quot; , &quot;ivoireCroatiaCubaCyprusCzech RepublicDjiboutiIDominicaDominican RepublicEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEthiopiaFalkland IslandsFaroe IslandsFijiFinlandFranceFrench GuianaFrench PolynesiaFrench Souther TerritoriesGabonGambiaGeorgiaGhanaGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuineaGuinea-BissauGuyanaHaitiHeard and McDonald IslandsHondurasHong KongHungaryIcelandIndiaIndonesiaIranIraqIrelandIsraelItalyJamaicaJapanJordanKazakhstanKenyaKiribatiKuwaitKyrgyzstanLao Peoples Democratic RepublicLatviaLebanonLesothoLiberiaLibyaLiechtensteinLithuaniaLuxembourgMacauMacedoniaMadagascarMalawiMalaysiaMaldivesMaliMaltaMarshall IslandsMartiniqueMauritaniaMauritiusMayotteMexicoMicronesia, Federated States ofMoldovaMonacoMongoliaMontserratMoroccoMozambiqueMyanamarNamibiaNauruNepalNetherlandsNew CaledoniaNicaraguaNigerNigeriaNiueNorfolk IslandNorth KoreaNorthern Mariana IslandsNorwayOmanPakistanPalauPanamaPapua New GuineaParaguayPeruPhilippinesPitcairn IslandsPolandPortugalPuerto RicoQatarReunionRomaniaRussian FederationRwandaSaint HelenaSaint Kitts and NevisSaint LuciaSaint Pierre and MiquelonSaint Vincent and The GrenadinesSamoaSan MarinoSao Tome and PrincipeSaudi ArabiaSenegalSeychellesSingaporeSlovakiaSloveniaSolomon IslandsSomaliaSouth AfricaSouth GeorgiaSouth KoreaSpainSri LankaSudanSurinameSvalbardand Jan Mayen IslandsSyriaTaiwanTajikistanTanzaniaThailandTogoTokelauTongaTrinidad and TobagoTunisiaTurkeyTurkmenistanTurks and Caicos IslandsTuvaluUgandaUkraineUnited Arab EmiratesUruguayUS Minor Outlying IslandsUzbekistanVanuatuVatican CityVenezualaVietnamVirgin Islands (GB)Virgin Islands (US)Wallis and Futuna IslandsWestern SaharaYemenZambiaZimbabweDrivers Licence Drivers Licence is required*  Promo       Search    &quot;))]</value>
      <webElementGuid>2a640470-634d-45b0-a0d9-2fc3aafcb7f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
