<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_7 Results</name>
   <tag></tag>
   <elementGuidId>184c3d9e-6105-4388-b44b-671be5689bd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rootPrimary']/div/div/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div/span/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cec02c12-4fc5-4779-bfd7-8d65becf758e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.$=10.0.1.0.0.1.1.$search-result.0.$ResultsGroup.$flexBlock-2022-04-29.1:$B.0.2.1.0</value>
      <webElementGuid>d3d2c57b-4f73-4c64-8711-26276a306e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7 Results</value>
      <webElementGuid>8b06c07b-891b-4990-a2ab-643fd925fac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootPrimary&quot;)/div[1]/div[@class=&quot;container-fluid thl-main-container&quot;]/div[@class=&quot;row main-bg&quot;]/div[1]/div[@class=&quot;col-xs-12 col-lg-9 col-lg-offset-3 col-xl-10 col-xl-offset-2 thl-search-container&quot;]/div[2]/div[@class=&quot;row thl-content-container&quot;]/div[@class=&quot;col-sm-12 thl-search-results-container&quot;]/div[1]/div[@class=&quot;row sub-section&quot;]/div[@class=&quot;col-xs-12 sub-section&quot;]/div[@class=&quot;row thl-sub-section-heading-brand&quot;]/span[1]/span[2]/span[1]</value>
      <webElementGuid>2cdf27db-ff27-4b7c-9089-67974a99ab3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rootPrimary']/div/div/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div/span/span[2]/span</value>
      <webElementGuid>e7f22b79-4589-4b8a-8c32-e672a9878775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW SEARCH'])[4]/following::span[6]</value>
      <webElementGuid>749bc196-71de-4862-ba12-613ce482351c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[12]/following::span[7]</value>
      <webElementGuid>e0c26e69-a511-40fd-8941-25a7111afaf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HiTop - 3 Berth'])[1]/preceding::span[2]</value>
      <webElementGuid>9c71661e-0918-4f5f-9301-cc3ce7fae141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automatic110L Fridge/FreezerGas Stove'])[1]/preceding::span[2]</value>
      <webElementGuid>cb414090-8c0d-44b5-b651-e194941e2e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7 Results']/parent::*</value>
      <webElementGuid>8f23627f-b1fa-4d88-8c3d-bea39e59e55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]/span</value>
      <webElementGuid>e640c14c-b6fe-413e-97fd-6c2b6ca530c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '7 Results' or . = '7 Results')]</value>
      <webElementGuid>06113313-d122-44b4-9bf0-b3bdac6f1dc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
