<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pick Up Date</name>
   <tag></tag>
   <elementGuidId>9217c3d4-ae49-4480-b108-d442d34f9fb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>35b04b84-1b78-46d7-9240-e758fec6608c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2fdb608b-31ef-4b8e-a2ac-0b1768ea2610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e2564b9e-8fc5-4281-bc1c-575a4cac57cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>[ formControl form_datePicker_pickUp ]</value>
      <webElementGuid>3ae4a78b-f6b3-478e-be62-314da348153b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pick Up Date</value>
      <webElementGuid>586009a1-996d-4b3e-af64-ff95d2224822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_main&quot;)/div[@class=&quot;[ formGroup odd pickCal ]&quot;]/div[@class=&quot;[ formLabel ]&quot;]/button[@class=&quot;[ formControl form_datePicker_pickUp ]&quot;]</value>
      <webElementGuid>7f2def5a-72be-4dca-a782-fcbc08a7db17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>44bc825d-b7d6-4baa-881d-9f772d7ac3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_main']/div[2]/div/button</value>
      <webElementGuid>950ebd18-4e14-4551-9b20-c402c24a2925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick Up Date'])[1]/following::button[1]</value>
      <webElementGuid>f427fe84-c1a6-4aa8-9e31-2e10d9bb3c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book your Motorhome'])[1]/following::button[1]</value>
      <webElementGuid>585a082f-6213-4270-be28-8853f0b87aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick Up Date is required*'])[1]/preceding::button[1]</value>
      <webElementGuid>a22d453a-2ff8-4ee5-8762-09c2b8f3b89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drop Off Date'])[1]/preceding::button[1]</value>
      <webElementGuid>6463d818-3a15-4faa-8b48-a9f2ce92d0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>cfc0730b-2e7d-4de5-80bd-3c4574540df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Pick Up Date' or . = 'Pick Up Date')]</value>
      <webElementGuid>d52e3381-7d2e-450b-865b-a0eab86b1b37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
