<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Book your Motorhome     Pick Up Date 3_c31b22</name>
   <tag></tag>
   <elementGuidId>f7d0902d-e058-4f51-a622-e92bba5e4aa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_main']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form_main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>ddae0905-6fdf-47ec-abb2-0c83d18992a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>[ bookingComponent ]  prepareCountry hasCountry</value>
      <webElementGuid>cbbe88a1-6c25-4ded-b3fd-6ae77c590fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_main</value>
      <webElementGuid>b8455f3a-5a52-4ac1-a153-ea55e2a82221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>8a84db46-892e-4805-87b2-0a436589c8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>https://booking.maui-rentals.com/search?cc=nz&amp;brand=mby&amp;ac=&amp;sc=rv&amp;vtype=rv&amp;</value>
      <webElementGuid>6ffd365f-4493-4303-991b-c1286879ba75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Book your Motorhome     Pick Up Date 30/04/2022  Pick Up Date is required*     Drop Off Date 14/05/2022  Drop Off Date is required*    PrevNextMay 2022MoTuWeThFrSaSu      12345678910111213141516171819202122232425262728293031        Pick up location Pick Up Location  AucklandChristchurchQueenstown           AucklandAucklandChristchurchQueenstown Pick Up Location is required*Drop Off LocationDrop Off Location  AucklandChristchurchQueenstown     ChristchurchAucklandChristchurchQueenstown Drop Off Location is required*   Passengers Passengers  Adults 1234562123456 Children 0123450012345    Drivers LicenceDrivers Licence AustraliaCanadaChinaDenmarkFranceGermanyNetherlandsNew ZealandSwedenSwitzerlandUnited KingdomUnited States of America--------------------AfghanistanAlbaniaAlgeriaAmerican SamoaAndoraAngolaAnguillaAntarcticaAntigua &amp; BarbadosArgentinaArmeniaArubaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBeninBermudaBoliviaBosnia and HerzegovinaBotswanaBouvet IslandBrazilBritish Indian Ocean TerritoryBruneiBulgariaBurkina FasoBurundiButanCambodiaCameroonCape VerdeCayman IslandsCental African RepublicChadChileChristmas IslandCocos (Keeling) IslandColombiaComorosCongoCook IslandCosta RicaCote D'ivoireCroatiaCubaCyprusCzech RepublicDjiboutiIDominicaDominican RepublicEast TimorEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEthiopiaFalkland IslandsFaroe IslandsFijiFinlandFrance, MetropolitanFrench GuianaFrench PolynesiaFrench Souther TerritoriesGabonGambiaGeorgiaGhanaGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuineaGuinea-BissauGuyanaHaitiHeard and McDonald IslandsHondurasHong KongHungaryIcelandIndiaIndonesiaIranIraqIrelandIsraelItalyJamaicaJapanJordanKazakhstanKenyaKiribatiKuwaitKyrgyzstanLao Peoples Democratic RepublicLatviaLebanonLesothoLiberiaLibyaLiechtensteinLithuaniaLuxembourgMacauMacedoniaMadagascarMalawiMalaysiaMaldivesMaliMaltaMarshall IslandsMartiniqueMauritaniaMauritiusMayotteMexicoMicronesia, Federated States ofMoldovaMonacoMongoliaMontserratMoroccoMozambiqueMyanamarNamibiaNauruNepalNetherlands AntillesNew CaledoniaNicaraguaNigerNigeriaNiueNorfolk IslandNorth KoreaNorthern Mariana IslandsNorwayOmanPakistanPalauPanamaPapua New GuineaParaguayPeruPhilippinesPitcairn IslandsPolandPortugalPuerto RicoQatarReunionRomaniaRussian FederationRwandaSaint HelenaSaint Kitts and NevisSaint LuciaSaint Pierre and MiquelonSaint Vincent and The GrenadinesSamoaSan MarinoSao Tome and PrincipeSaudi ArabiaSenegalSeychellesSingaporeSlovakiaSloveniaSolomon IslandsSomaliaSouth AfricaSouth GeorgiaSouth KoreaSpainSri LankaSudanSurinameSvalbardand Jan Mayen IslandsSyriaTahitiTaiwanTajikistanTanzaniaThailandTogoTokelauTongaTrinidad and TobagoTunisiaTurkeyTurkmenistanTurks and Caicos IslandsTuvaluUgandaUkraineUnited Arab EmiratesUruguayUS Minor Outlying IslandsUzbekistanVanuatuVatican CityVenezualaVietnamVirgin Islands (GB)Virgin Islands (US)Wallis and Futuna IslandsWestern SaharaYemenYugoslaviaZaireZambiaZimbabweDrivers Licence Drivers Licence is required*  Promo      Search    </value>
      <webElementGuid>9c149297-47a3-4087-825a-430c3e11aa97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_main&quot;)</value>
      <webElementGuid>ac61c7b3-832e-4004-b09f-47d81b90e5e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='form_main']</value>
      <webElementGuid>0de14cf4-6f0b-4b41-af74-554bf04c9b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Australia'])[2]/following::form[1]</value>
      <webElementGuid>273e69c5-041d-41cc-9a7f-9c277b974a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Zealand'])[3]/following::form[1]</value>
      <webElementGuid>a370c2f4-fd75-4938-98f6-12fe815ee9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>a93c88d4-3792-4e2c-ac0a-cda17205fc17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'form_main' and (text() = concat(&quot;    Book your Motorhome     Pick Up Date 30/04/2022  Pick Up Date is required*     Drop Off Date 14/05/2022  Drop Off Date is required*    PrevNextMay 2022MoTuWeThFrSaSu      12345678910111213141516171819202122232425262728293031        Pick up location Pick Up Location  AucklandChristchurchQueenstown           AucklandAucklandChristchurchQueenstown Pick Up Location is required*Drop Off LocationDrop Off Location  AucklandChristchurchQueenstown     ChristchurchAucklandChristchurchQueenstown Drop Off Location is required*   Passengers Passengers  Adults 1234562123456 Children 0123450012345    Drivers LicenceDrivers Licence AustraliaCanadaChinaDenmarkFranceGermanyNetherlandsNew ZealandSwedenSwitzerlandUnited KingdomUnited States of America--------------------AfghanistanAlbaniaAlgeriaAmerican SamoaAndoraAngolaAnguillaAntarcticaAntigua &amp; BarbadosArgentinaArmeniaArubaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBeninBermudaBoliviaBosnia and HerzegovinaBotswanaBouvet IslandBrazilBritish Indian Ocean TerritoryBruneiBulgariaBurkina FasoBurundiButanCambodiaCameroonCape VerdeCayman IslandsCental African RepublicChadChileChristmas IslandCocos (Keeling) IslandColombiaComorosCongoCook IslandCosta RicaCote D&quot; , &quot;'&quot; , &quot;ivoireCroatiaCubaCyprusCzech RepublicDjiboutiIDominicaDominican RepublicEast TimorEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEthiopiaFalkland IslandsFaroe IslandsFijiFinlandFrance, MetropolitanFrench GuianaFrench PolynesiaFrench Souther TerritoriesGabonGambiaGeorgiaGhanaGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuineaGuinea-BissauGuyanaHaitiHeard and McDonald IslandsHondurasHong KongHungaryIcelandIndiaIndonesiaIranIraqIrelandIsraelItalyJamaicaJapanJordanKazakhstanKenyaKiribatiKuwaitKyrgyzstanLao Peoples Democratic RepublicLatviaLebanonLesothoLiberiaLibyaLiechtensteinLithuaniaLuxembourgMacauMacedoniaMadagascarMalawiMalaysiaMaldivesMaliMaltaMarshall IslandsMartiniqueMauritaniaMauritiusMayotteMexicoMicronesia, Federated States ofMoldovaMonacoMongoliaMontserratMoroccoMozambiqueMyanamarNamibiaNauruNepalNetherlands AntillesNew CaledoniaNicaraguaNigerNigeriaNiueNorfolk IslandNorth KoreaNorthern Mariana IslandsNorwayOmanPakistanPalauPanamaPapua New GuineaParaguayPeruPhilippinesPitcairn IslandsPolandPortugalPuerto RicoQatarReunionRomaniaRussian FederationRwandaSaint HelenaSaint Kitts and NevisSaint LuciaSaint Pierre and MiquelonSaint Vincent and The GrenadinesSamoaSan MarinoSao Tome and PrincipeSaudi ArabiaSenegalSeychellesSingaporeSlovakiaSloveniaSolomon IslandsSomaliaSouth AfricaSouth GeorgiaSouth KoreaSpainSri LankaSudanSurinameSvalbardand Jan Mayen IslandsSyriaTahitiTaiwanTajikistanTanzaniaThailandTogoTokelauTongaTrinidad and TobagoTunisiaTurkeyTurkmenistanTurks and Caicos IslandsTuvaluUgandaUkraineUnited Arab EmiratesUruguayUS Minor Outlying IslandsUzbekistanVanuatuVatican CityVenezualaVietnamVirgin Islands (GB)Virgin Islands (US)Wallis and Futuna IslandsWestern SaharaYemenYugoslaviaZaireZambiaZimbabweDrivers Licence Drivers Licence is required*  Promo      Search    &quot;) or . = concat(&quot;    Book your Motorhome     Pick Up Date 30/04/2022  Pick Up Date is required*     Drop Off Date 14/05/2022  Drop Off Date is required*    PrevNextMay 2022MoTuWeThFrSaSu      12345678910111213141516171819202122232425262728293031        Pick up location Pick Up Location  AucklandChristchurchQueenstown           AucklandAucklandChristchurchQueenstown Pick Up Location is required*Drop Off LocationDrop Off Location  AucklandChristchurchQueenstown     ChristchurchAucklandChristchurchQueenstown Drop Off Location is required*   Passengers Passengers  Adults 1234562123456 Children 0123450012345    Drivers LicenceDrivers Licence AustraliaCanadaChinaDenmarkFranceGermanyNetherlandsNew ZealandSwedenSwitzerlandUnited KingdomUnited States of America--------------------AfghanistanAlbaniaAlgeriaAmerican SamoaAndoraAngolaAnguillaAntarcticaAntigua &amp; BarbadosArgentinaArmeniaArubaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBeninBermudaBoliviaBosnia and HerzegovinaBotswanaBouvet IslandBrazilBritish Indian Ocean TerritoryBruneiBulgariaBurkina FasoBurundiButanCambodiaCameroonCape VerdeCayman IslandsCental African RepublicChadChileChristmas IslandCocos (Keeling) IslandColombiaComorosCongoCook IslandCosta RicaCote D&quot; , &quot;'&quot; , &quot;ivoireCroatiaCubaCyprusCzech RepublicDjiboutiIDominicaDominican RepublicEast TimorEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEthiopiaFalkland IslandsFaroe IslandsFijiFinlandFrance, MetropolitanFrench GuianaFrench PolynesiaFrench Souther TerritoriesGabonGambiaGeorgiaGhanaGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuineaGuinea-BissauGuyanaHaitiHeard and McDonald IslandsHondurasHong KongHungaryIcelandIndiaIndonesiaIranIraqIrelandIsraelItalyJamaicaJapanJordanKazakhstanKenyaKiribatiKuwaitKyrgyzstanLao Peoples Democratic RepublicLatviaLebanonLesothoLiberiaLibyaLiechtensteinLithuaniaLuxembourgMacauMacedoniaMadagascarMalawiMalaysiaMaldivesMaliMaltaMarshall IslandsMartiniqueMauritaniaMauritiusMayotteMexicoMicronesia, Federated States ofMoldovaMonacoMongoliaMontserratMoroccoMozambiqueMyanamarNamibiaNauruNepalNetherlands AntillesNew CaledoniaNicaraguaNigerNigeriaNiueNorfolk IslandNorth KoreaNorthern Mariana IslandsNorwayOmanPakistanPalauPanamaPapua New GuineaParaguayPeruPhilippinesPitcairn IslandsPolandPortugalPuerto RicoQatarReunionRomaniaRussian FederationRwandaSaint HelenaSaint Kitts and NevisSaint LuciaSaint Pierre and MiquelonSaint Vincent and The GrenadinesSamoaSan MarinoSao Tome and PrincipeSaudi ArabiaSenegalSeychellesSingaporeSlovakiaSloveniaSolomon IslandsSomaliaSouth AfricaSouth GeorgiaSouth KoreaSpainSri LankaSudanSurinameSvalbardand Jan Mayen IslandsSyriaTahitiTaiwanTajikistanTanzaniaThailandTogoTokelauTongaTrinidad and TobagoTunisiaTurkeyTurkmenistanTurks and Caicos IslandsTuvaluUgandaUkraineUnited Arab EmiratesUruguayUS Minor Outlying IslandsUzbekistanVanuatuVatican CityVenezualaVietnamVirgin Islands (GB)Virgin Islands (US)Wallis and Futuna IslandsWestern SaharaYemenYugoslaviaZaireZambiaZimbabweDrivers Licence Drivers Licence is required*  Promo      Search    &quot;))]</value>
      <webElementGuid>2c9f5dc0-423c-4e4a-9403-48de821a886a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
